services:
  protest-db:
    container_name: protest-db
    image: postgres:17-alpine
    environment:
      - CREATE_DATABASES=protest-auth,protest-projects,protest-cases,protest-runs
      - PGUSER=postgres
      - POSTGRES_PASSWORD=password
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
    volumes:
      - ./postgres/script:/docker-entrypoint-initdb.d
      - protest-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "15432:5432"
    command: [ "postgres", "-c", "max_prepared_transactions=100" ]
    networks:
      - protest-network

  protest-kafka:
    container_name: protest-kafka
    image: apache/kafka:3.7.0
    ports:
      - "19092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:19092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs
    networks:
      - protest-network

  protest-minio:
    container_name: protest-minio
    image: minio/minio:RELEASE.2024-01-28T22-35-53Z
    ports:
      - "19000:9000"
      - "19001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - protest-miniodata:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - protest-network

  protest-wiremock:
    container_name: protest-wiremock
    image: wiremock/wiremock:3.4.2-1
    ports:
      - "8089:8080"
    volumes:
      - ./wiremock:/home/wiremock
    command:
      - --global-response-templating
    networks:
      - protest-network

volumes:
  protest-pgdata:
  protest-miniodata:

networks:
  protest-network:
    driver: bridge
