server:
  port: 8093

spring:
  application:
    name: protest-runs
  datasource:
    url: jdbc:postgresql://localhost:15432/protest-runs
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  kafka:
    bootstrap-servers: localhost:19092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: protest-runs-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        "[spring.json.trusted.packages]": "io.protest.webutils.event"
  flyway:
    enabled: true

logging:
  level:
    org.springframework.web: DEBUG
