server:
  port: 8080
spring:
  application:
    name: protest-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  web:
    error:
      include-message: always

protest:
  services: 
    auth-url: http://localhost:9000
    projects-url: http://localhost:8091
    testcases-url: http://localhost:8092
    runs-url: http://localhost:8093

