server:
  port: 9000

spring:
  application:
    name: protest-auth
  datasource:
    url: jdbc:postgresql://localhost:15432/protest-auth
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
