import React, { useState } from 'react';
import { Sparkles, Copy, Check, MessageSquare, Code } from 'lucide-react';

export const AiAssistant = ({ activeCase, activeRunCase, cases }) => {
  const [query, setQuery] = useState('');
  const [response, setResponse] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [copied, setCopied] = useState(false);

  const currentCase = activeCase || (activeRunCase && cases.find(c => c.id === activeRunCase.testcaseId));

  const handleCopy = () => {
    navigator.clipboard.writeText(response);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const generateSteps = () => {
    if (!currentCase) {
      setResponse("⚠️ Пожалуйста, выберите или создайте тест-кейс в репозитории для генерации шагов.");
      return;
    }
    setIsLoading(true);
    setTimeout(() => {
      const generated = `[AI GENERATED STEPS for: "${currentCase.title}"]
1. Открыть главную страницу приложения.
2. Перейти в раздел авторизации/регистрации.
3. Ввести валидные тестовые данные (email: test_${Date.now()}@protest.io).
4. Нажать кнопку подтверждения действия.
5. Проверить успешный статус операции (HTTP 200 OK / появление токена).`;
      setResponse(generated);
      setIsLoading(false);
    }, 1200);
  };

  const generateJUnitTest = () => {
    if (!currentCase) {
      setResponse("⚠️ Выберите тест-кейс, чтобы сгенерировать JUnit автотест.");
      return;
    }

    setIsLoading(true);
    setTimeout(() => {
      const steps = currentCase.steps || [];
      const testName = currentCase.title
        .replace(/[^a-zA-Zа-яА-Я0-9]/g, ' ')
        .split(' ')
        .map((word, idx) => {
          if (!word) return '';
          const enWord = transliterate(word);
          return idx === 0 ? enWord.toLowerCase() : enWord.charAt(0).toUpperCase() + enWord.slice(1);
        })
        .join('');

      let stepsComments = '';
      steps.forEach((s, idx) => {
        stepsComments += `        // Шаг ${idx + 1}: ${s.action}\n`;
        if (s.expected) {
          stepsComments += `        // Ожидаемый результат: ${s.expected}\n`;
        }
        stepsComments += `        // TODO: Реализовать шаг\n\n`;
      });

      const javaCode = `package io.protest.tests;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import static io.restassured.RestAssured.*;
import static org.hamcrest.Matchers.*;

public class ProTestAutoGeneratedIT {

    @Test
    @DisplayName("${currentCase.title}")
    void ${testName || 'testGeneratedCode'}() {
        // Слой тестирования: ${currentCase.layer || 'UI'}
        // Автоматизировано с помощью ProTEST AI Assist

${stepsComments || '        // Нет шагов для генерации кода автотеста.\n'}
        given()
            .header("Content-Type", "application/json")
        .when()
            .get("/api/health")
        .then()
            .statusCode(200);
    }
}`;
      setResponse(javaCode);
      setIsLoading(false);
    }, 1500);
  };

  const transliterate = (word) => {
    const map = {
      'а':'a','б':'b','в':'v','г':'g','д':'d','е':'e','ё':'yo','ж':'zh','з':'z','и':'i','й':'y','к':'k','л':'l','м':'m','н':'n','о':'o','п':'p','р':'r','с':'s','т':'t','у':'u','ф':'f','х':'h','ц':'ts','ч':'ch','ш':'sh','щ':'sch','ъ':'','ы':'y','ь':'','э':'e','ю':'yu','я':'ya',
      'А':'A','Б':'B','В':'V','Г':'G','Д':'D','Е':'E','Ё':'Yo','Ж':'Zh','З':'Z','И':'I','Й':'Y','К':'K','Л':'L','М':'M','Н':'N','О':'O','П':'P','Р':'R','С':'S','Т':'T','У':'U','Ф':'F','Х':'H','Ц':'Ts','Ч':'Ch','Ш':'Sh','Щ':'Sch','Ъ':'','Ы':'Y','Ь':'','Э':'E','Ю':'Yu','Я':'Ya'
    };
    return word.split('').map(c => map[c] || c).join('');
  };

  const handleCustomQuery = (e) => {
    e.preventDefault();
    if (!query.trim()) return;

    setIsLoading(true);
    setTimeout(() => {
      const q = query.toLowerCase();
      let res = '';
      if (q.includes('привет') || q.includes('hello')) {
        res = "Привет! Я твой встроенный ИИ-помощник ProTEST. Я могу помочь тебе составить шаги тест-кейса, сгенерировать Java/JUnit автотест на базе RestAssured, или подсказать идеи для негативных тестов. Выбери тест-кейс и воспользуйся быстрыми командами выше!";
      } else if (q.includes('негатив') || q.includes('negative')) {
        res = `[AI ИДЕИ ДЛЯ НЕГАТИВНЫХ ТЕСТОВ]\n1. Граничные значения: отправить пустую строку или слишком длинный текст.\n2. SQL-инъекции: вставить "' OR '1'='1" в текстовые поля.\n3. Спецсимволы: отправить JSON с символами emoji, <script>alert(1)</script> (XSS).\n4. Авторизация: попробовать выполнить запрос без Bearer-токена.`;
      } else {
        res = `[AI Ответ на: "${query}"]\nОтличный вопрос! Для реализации этой проверки на бэкенде рекомендуется добавить интеграционный тест на RestAssured. Убедись, что сервис "gateway" и микросервис "runs" запущены в твоем окружении, а база данных PostgreSQL активна.`;
      }
      setResponse(res);
      setQuery('');
      setIsLoading(false);
    }, 1000);
  };

  return (
    <div className="flex flex-col h-full gap-4">
      <div className="flex items-center gap-2 pb-2 border-b border-[#30363d]">
        <Sparkles size={16} className="text-[#58a6ff]" />
        <h3 className="text-sm font-semibold text-[#f0f6fc]">AI Assistant</h3>
      </div>

      {currentCase ? (
        <div className="rounded-lg border border-[#30363d] bg-[#0d1117]/50 p-3 text-xs flex flex-col gap-1">
          <span className="text-[10px] text-[#8b949e] font-semibold uppercase">Выбран тест-кейс:</span>
          <span className="text-[#f0f6fc] font-medium truncate">{currentCase.title}</span>
          <span className="text-[10px] text-[#58a6ff]">{currentCase.layer || 'UI'} • {currentCase.isAutomated ? 'Авто' : 'Ручной'}</span>
        </div>
      ) : (
        <div className="rounded-lg border border-[#30363d]/50 bg-[#0d1117]/20 p-3 text-xs text-[#8b949e] italic text-center">
          Кейс не выбран. Выберите тест-кейс для работы ИИ.
        </div>
      )}

      {/* Быстрые команды */}
      <div className="flex flex-col gap-2">
        <span className="text-[10px] text-[#8b949e] font-semibold uppercase">Быстрые AI команды:</span>
        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={generateSteps}
            className="btn btn-default py-2 text-xs font-semibold flex items-center justify-center gap-1.5 w-full"
          >
            <MessageSquare size={12} /> Набросать шаги
          </button>
          <button
            onClick={generateJUnitTest}
            className="btn btn-default py-2 text-xs font-semibold flex items-center justify-center gap-1.5 w-full"
          >
            <Code size={12} /> Сделать автотест
          </button>
        </div>
      </div>

      {/* Вывод ответа */}
      <div className="flex-grow flex flex-col gap-2 min-h-0">
        <div className="flex justify-between items-center text-[10px] text-[#8b949e] font-semibold uppercase">
          <span>Результат генерации:</span>
          {response && (
            <button
              onClick={handleCopy}
              className="flex items-center gap-1 text-[#58a6ff] hover:underline cursor-pointer"
            >
              {copied ? <Check size={10} /> : <Copy size={10} />}
              {copied ? 'Скопировано!' : 'Копировать'}
            </button>
          )}
        </div>

        <div className="flex-grow rounded-lg border border-[#30363d] bg-[#0d1117] p-3 overflow-y-auto min-h-[150px] relative">
          {isLoading ? (
            <div className="absolute inset-0 flex items-center justify-center bg-[#0d1117]/85">
              <span className="w-5 h-5 border-2 border-[#58a6ff] border-t-transparent rounded-full animate-spin" />
            </div>
          ) : null}
          {response ? (
            <pre className="font-mono text-xs text-[#c9d1d9] whitespace-pre-wrap select-text leading-relaxed">
              {response}
            </pre>
          ) : (
            <span className="text-xs text-[#8b949e] italic block text-center mt-8">
              Здесь появится ответ ИИ-ассистента
            </span>
          )}
        </div>
      </div>

      {/* Форма запроса */}
      <form onSubmit={handleCustomQuery} className="flex gap-2 mt-auto">
        <input
          type="text"
          className="flex-grow rounded-[6px] border border-[#30363d] bg-[#0d1117] px-3 py-2 text-xs text-[#e6edf3] transition-[border-color,box-shadow] duration-150 focus:border-[#58a6ff] focus:outline-none focus:shadow-[0_0_0_3px_rgba(88,166,255,0.15)]"
          placeholder="Спросить ИИ-помощника..."
          value={query}
          onChange={e => setQuery(e.target.value)}
        />
        <button
          type="submit"
          className="btn btn-accent px-3 py-2 text-xs font-semibold"
        >
          Отправить
        </button>
      </form>
    </div>
  );
};
